- name: Setup
  hosts: localhost
  connection: local

  vars:
    system_packages:
      - fish
    flatpak_apps:
      - org.mozilla.firefox
      - dev.zed.Zed
      - com.rioterm.Rio
      - md.obsidian.Obsidian
    uv_tools:
      - ruff
      - ty
    dev_tools:
      - helix
      - ripgrep
      - yadm
      - starship
      - bat

  tasks:
    # Packages
    - name: Install System Packages
      community.general.rpm_ostree_pkg:
        name: "{{ system_packages }}"
        state: present
      register: ostree_result

    # uv
    - name: Install uv tools
      command:
        cmd: "uv tool install {{ item }}"
      loop: "{{ uv_tools }}"

    # Flathub
    - name: Enable Flathub Repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install Flatpak Applications
      community.general.flatpak:
        name: "{{ item }}"
        remote: flathub
        state: present
      loop: "{{ flatpak_apps }}"

    # Homebrew
    - name: Install Homebrew
      shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Install dev tools
      command:
        cmd: "brew install {{ item }}"
      loop: "{{ dev_tools }}"

    # Dotfiles
    - name: Check dotfiles
      ansible.builtin.stat:
        path: "{{ ansible_facts.env.HOME }}/.local/share/yadm/repo.git"
      register: yadm_repo

    - name: Clone dotfiles
      command:
        cmd: "yadm clone {{url}}"
      when: not yadm_repo.stat.exists
      vars:
        url: "https://github.com/HeitorHenz/dotfiles.git"

    - name: Create minimal bootstrap
      ansible.builtin.copy:
        dest: "{{ ansible_user_dir }}/.config/yadm/bootstrap"
        content: |
          #!/bin/bash
          yadm alt
        mode: "0755"
        when: not yadm_repo.stat.exists

    - name: Run bootstrap
      ansible.builtin.command:
        cmd: "yadm bootstrap"
      when: not yadm_repo.stat.exists

    # Reboot
    - name: Notify User of Reboot Requirement
      reboot:
        msg: "Rebooting"
      when: ostree_result.changed
