- name: Setup
  hosts: localhost
  connection: local

  vars:
    system_packages:
      - fish
      - helix
      - stow
    flatpak_apps:
      - org.mozilla.firefox
      - dev.zed.Zed
      - com.rioterm.Rio
      - md.obsidian.Obsidian
    uv_tools:
      - ruff
      - ty
    cargo_tools:
      - ripgrep
      - starship
      - bat
      - uv

  tasks:
    # Packages
    - name: Install System Packages
      become: true
      ansible.builtin.dnf:
        name: "{{ system_packages }}"
        state: present

    # Rustup
    - name: Install rustup
      ansible.builtin.shell:
        cmd: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
        creates: "{{ lookup('env', 'HOME') }}/.cargo/bin/rustup"

    # Cargo
    - name: Install cargo tools
      community.general.cargo:
        name: "{{ item }}"
        state: present
      loop: "{{ cargo_tools }}"

    # uv tools
    - name: Install uv tools
      ansible.builtin.shell::
        cmd: "uv tool install {{ item }}"
      loop: "{{ uv_tools }}"

    # Flathub
    - name: Enable Flathub Repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install Flatpak Applications
      community.general.flatpak:
        name: "{{ item }}"
        remote: flathub
        state: present
      loop: "{{ flatpak_apps }}"

    # Stow
    - name: Stow all dotfiles dynamically
      ansible.builtin.shell: stow -R */
      args:
        chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
