- name: Setup
  hosts: localhost
  connection: local
  become: true

  vars:
    system_packages:
      - fish
      - git
      - rustup
      - helix
    flatpak_apps:
      - org.mozilla.firefox
      - dev.zed.Zed
      - com.rioterm.Rio
      - md.obsidian.Obsidian
    uv_tools:
      - ruff
      - ty

  tasks:
    # Uv
    - name: Install uv tools
      command:
        cmd: "uv tool install {{ item }}"
      loop: "{{ uv_tools }}"

    # Flathub
    - name: Enable Flathub Repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install Flatpak Applications
      community.general.flatpak:
        name: "{{ item }}"
        remote: flathub
        state: present
      loop: "{{ flatpak_apps }}"

    # yadm

    - name: Install yadm
      become: true
      ansible.builtin.get_url:
        url: https://github.com/yadm-dev/yadm/raw/master/yadm
        dest: /usr/local/bin/yadm
        mode: "0755"

    - name: Check dotfiles
      ansible.builtin.stat:
        path: "{{ ansible_facts.env.HOME }}/.local/share/yadm/repo.git"
      register: yadm_repo

    - name: Install yadm
      command:
        cmd: "yadm clone {{url}} --bootstrap"
      when: not yadm_repo.stat.exists
      vars:
        url: "https://github.com/HeitorHenz/dotfiles.git"

    - name: Create minimal bootstrap
      ansible.builtin.copy:
        dest: "{{ ansible_user_dir }}/.config/yadm/bootstrap"
        content: |
          #!/bin/bash
          yadm alt
        mode: "0755"
      when: ansible_facts.stat.exists is not defined or not ansible_facts.stat.exists

    - name: Run bootstrap
      ansible.builtin.command:
        cmd: "yadm bootstrap"

    # Packages
    - name: Install Layered System Packages
      community.general.rpm_ostree_pkg:
        name: "{{ system_packages }}"
        state: present
      register: ostree_result

    # Reboot
    - name: Notify User of Reboot Requirement
      reboot:
        msg: "Rebooting"
      when: ostree_result.changed
